name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
env:
  NODE_VERSION: '20.x'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    -name: Test
      run: ls -l
    - name: Install webpack
      run: npm install npm install -D webpack-cli

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build


    - name: Deploy
      run: |
        npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

    - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MAIN_ACCESS }}
          publish_dir: ./dist

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    -name: Test
      run: ls -l